import { Router } from "express";
import Anthropic from "@anthropic-ai/sdk";
import { requireAuth } from "../auth.js";
import { db } from "../db.js";
import { getChain, verifyChain } from "../crypto.js";
import { flags, centers, liveStats } from "../store.js";

export const reportRouter = Router();

const client = process.env.ANTHROPIC_API_KEY ? new Anthropic() : null;

function buildStats() {
  const totalRequests = (db.prepare("SELECT COUNT(*) as cnt FROM audit_log").get() as { cnt: number }).cnt;
  const blocked = (db.prepare("SELECT COUNT(*) as cnt FROM audit_log WHERE status IN (401, 423)").get() as { cnt: number }).cnt;

  const flagsConfirmed = flags.filter((f) => f.status === "confirmed").length;
  const flagsDismissed = flags.filter((f) => f.status === "dismissed").length;
  const flagsOpen = flags.filter((f) => f.status === "open").length;
  const totalFlags = flagsConfirmed + flagsDismissed + flagsOpen;

  const chain = getChain();
  const chainStatus = verifyChain();
  const scheduleBlock = chain.find((b) => b.event === "exam_scheduled");
  const examStartIso = scheduleBlock ? (scheduleBlock.data.startAt as string) : null;

  return {
    examWindow: { startAt: examStartIso ?? "Not recorded" },
    security: {
      totalApiRequests: totalRequests,
      unauthorizedBlocked: blocked,
      blockRate: totalRequests > 0 ? `${((blocked / totalRequests) * 100).toFixed(1)}%` : "0%",
    },
    proctoring: {
      totalFlagsRaised: totalFlags,
      confirmed: flagsConfirmed,
      dismissed: flagsDismissed,
      stillOpen: flagsOpen,
      falsePositiveRate:
        flagsConfirmed + flagsDismissed > 0
          ? `${((flagsDismissed / (flagsConfirmed + flagsDismissed)) * 100).toFixed(1)}%`
          : "n/a",
    },
    integrity: {
      chainLength: chain.length,
      chainValid: chainStatus.valid,
      brokenAtBlock: chainStatus.brokenAt,
    },
    distribution: {
      centersDeployed: centers.filter((c) => c.status !== "idle").length,
      papersAssembled: liveStats.papersAssembled,
      fairnessScore: liveStats.lastFairness,
    },
  };
}

function fallbackReport(stats: ReturnType<typeof buildStats>): string {
  const s = stats;
  return [
    `POST-EXAM SECURITY INTELLIGENCE REPORT`,
    `Generated by Parakh — ${new Date().toUTCString()}`,
    ``,
    `EXAM OVERVIEW`,
    `Examination conducted at ${s.examWindow.startAt}. ${s.distribution.centersDeployed} examination centres deployed across the network. ${s.distribution.papersAssembled} cryptographically sealed paper variant(s) distributed. AI fairness score: ${s.distribution.fairnessScore ?? "n/a"}/100.`,
    ``,
    `SECURITY POSTURE`,
    `Total API requests processed: ${s.security.totalApiRequests}. Unauthorized access attempts blocked: ${s.security.unauthorizedBlocked} (${s.security.blockRate} block rate). All content remained encrypted at rest via AES-256-GCM throughout the examination window. Zero human translators accessed paper content.`,
    ``,
    `AI PROCTORING ANALYSIS`,
    `Proctoring engine raised ${s.proctoring.totalFlagsRaised} anomaly flags during the session. Human invigilators confirmed ${s.proctoring.confirmed} flag(s) as genuine incidents and dismissed ${s.proctoring.dismissed} as false positives (false positive rate: ${s.proctoring.falsePositiveRate}). ${s.proctoring.stillOpen} flag(s) remain pending human review. AI acted as detection engine only — all decisions made by authorised personnel.`,
    ``,
    `INTEGRITY VERDICT`,
    s.integrity.chainValid
      ? `SHA-256 hash chain verified intact across all ${s.integrity.chainLength} blocks. Every candidate assignment, paper distribution, flag decision, and evaluation event is cryptographically sealed. No tampering detected. Result ledger is publicly auditable.`
      : `WARNING: Hash chain integrity failure detected at block #${s.integrity.brokenAtBlock}. All records after this block are untrusted. Immediate audit required before results are published.`,
  ].join("\n");
}

reportRouter.post("/", requireAuth("teacher", "admin"), async (_req, res) => {
  const stats = buildStats();

  if (!client) {
    res.json({ report: fallbackReport(stats) });
    return;
  }

  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Transfer-Encoding", "chunked");
  res.setHeader("Cache-Control", "no-cache");

  try {
    const stream = client.messages.stream({
      model: "claude-opus-4-8",
      max_tokens: 700,
      system: `You are Parakh's post-exam security intelligence engine for Indian board examinations.
Generate a formal threat analysis report. Rules:
- Plain text only, NO markdown, NO bullet points, NO asterisks, NO headers with #
- Four paragraphs separated by blank lines
- Paragraph 1: Exam overview and deployment summary
- Paragraph 2: Unauthorized access attempts — what was blocked and how
- Paragraph 3: AI proctoring performance — flags, human decisions, false positive rate
- Paragraph 4: Hash chain integrity verdict and final security assessment
- Tone: authoritative, formal, like an Indian government security communiqué
- 160-220 words total
- Begin with "SECURITY INTELLIGENCE REPORT — Parakh" on the first line`,
      messages: [
        {
          role: "user",
          content: `Generate the post-exam security report using these aggregated statistics (no PII included):\n\n${JSON.stringify(stats, null, 2)}`,
        },
      ],
    });

    for await (const chunk of stream) {
      if (chunk.type === "content_block_delta" && chunk.delta.type === "text_delta") {
        res.write(chunk.delta.text);
      }
    }
    res.end();
  } catch (err) {
    console.error("Report generation failed:", err instanceof Error ? err.message : err);
    res.write(fallbackReport(stats));
    res.end();
  }
});
